###############################################################################
# Created by write_sdc
# Tue Sep  5 16:00:05 2023
###############################################################################
current_design z23
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 100.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {interrupt_gpio_in}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[0]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[10]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[11]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[12]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[13]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[14]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[15]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[1]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[2]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[3]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[4]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[5]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[6]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[7]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[8]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {keypad_input[9]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[0]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[1]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[2]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[3]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[4]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[5]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[6]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_in[7]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {nrst}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[0]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[1]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[2]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[3]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[4]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[5]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[6]}]
set_input_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_in[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[10]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[11]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[12]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[13]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[14]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[15]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[8]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_address_out[9]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_data_out[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {memory_wr}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_out[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {programmable_gpio_wr[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss0[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss1[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss2[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss3[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss4[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss5[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss6[7]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[0]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[1]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[2]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[3]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[4]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[5]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[6]}]
set_output_delay 20.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ss7[7]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {memory_wr}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[15]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[14]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[13]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[12]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[11]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[10]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[9]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[8]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[7]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[6]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[5]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[4]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[3]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[2]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[1]}]
set_load -pin_load 0.0334 [get_ports {memory_address_out[0]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[7]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[6]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[5]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[4]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[3]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[2]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[1]}]
set_load -pin_load 0.0334 [get_ports {memory_data_out[0]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[7]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[6]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[5]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[4]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[3]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[2]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[1]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_out[0]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[7]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[6]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[5]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[4]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[3]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[2]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[1]}]
set_load -pin_load 0.0334 [get_ports {programmable_gpio_wr[0]}]
set_load -pin_load 0.0334 [get_ports {ss0[7]}]
set_load -pin_load 0.0334 [get_ports {ss0[6]}]
set_load -pin_load 0.0334 [get_ports {ss0[5]}]
set_load -pin_load 0.0334 [get_ports {ss0[4]}]
set_load -pin_load 0.0334 [get_ports {ss0[3]}]
set_load -pin_load 0.0334 [get_ports {ss0[2]}]
set_load -pin_load 0.0334 [get_ports {ss0[1]}]
set_load -pin_load 0.0334 [get_ports {ss0[0]}]
set_load -pin_load 0.0334 [get_ports {ss1[7]}]
set_load -pin_load 0.0334 [get_ports {ss1[6]}]
set_load -pin_load 0.0334 [get_ports {ss1[5]}]
set_load -pin_load 0.0334 [get_ports {ss1[4]}]
set_load -pin_load 0.0334 [get_ports {ss1[3]}]
set_load -pin_load 0.0334 [get_ports {ss1[2]}]
set_load -pin_load 0.0334 [get_ports {ss1[1]}]
set_load -pin_load 0.0334 [get_ports {ss1[0]}]
set_load -pin_load 0.0334 [get_ports {ss2[7]}]
set_load -pin_load 0.0334 [get_ports {ss2[6]}]
set_load -pin_load 0.0334 [get_ports {ss2[5]}]
set_load -pin_load 0.0334 [get_ports {ss2[4]}]
set_load -pin_load 0.0334 [get_ports {ss2[3]}]
set_load -pin_load 0.0334 [get_ports {ss2[2]}]
set_load -pin_load 0.0334 [get_ports {ss2[1]}]
set_load -pin_load 0.0334 [get_ports {ss2[0]}]
set_load -pin_load 0.0334 [get_ports {ss3[7]}]
set_load -pin_load 0.0334 [get_ports {ss3[6]}]
set_load -pin_load 0.0334 [get_ports {ss3[5]}]
set_load -pin_load 0.0334 [get_ports {ss3[4]}]
set_load -pin_load 0.0334 [get_ports {ss3[3]}]
set_load -pin_load 0.0334 [get_ports {ss3[2]}]
set_load -pin_load 0.0334 [get_ports {ss3[1]}]
set_load -pin_load 0.0334 [get_ports {ss3[0]}]
set_load -pin_load 0.0334 [get_ports {ss4[7]}]
set_load -pin_load 0.0334 [get_ports {ss4[6]}]
set_load -pin_load 0.0334 [get_ports {ss4[5]}]
set_load -pin_load 0.0334 [get_ports {ss4[4]}]
set_load -pin_load 0.0334 [get_ports {ss4[3]}]
set_load -pin_load 0.0334 [get_ports {ss4[2]}]
set_load -pin_load 0.0334 [get_ports {ss4[1]}]
set_load -pin_load 0.0334 [get_ports {ss4[0]}]
set_load -pin_load 0.0334 [get_ports {ss5[7]}]
set_load -pin_load 0.0334 [get_ports {ss5[6]}]
set_load -pin_load 0.0334 [get_ports {ss5[5]}]
set_load -pin_load 0.0334 [get_ports {ss5[4]}]
set_load -pin_load 0.0334 [get_ports {ss5[3]}]
set_load -pin_load 0.0334 [get_ports {ss5[2]}]
set_load -pin_load 0.0334 [get_ports {ss5[1]}]
set_load -pin_load 0.0334 [get_ports {ss5[0]}]
set_load -pin_load 0.0334 [get_ports {ss6[7]}]
set_load -pin_load 0.0334 [get_ports {ss6[6]}]
set_load -pin_load 0.0334 [get_ports {ss6[5]}]
set_load -pin_load 0.0334 [get_ports {ss6[4]}]
set_load -pin_load 0.0334 [get_ports {ss6[3]}]
set_load -pin_load 0.0334 [get_ports {ss6[2]}]
set_load -pin_load 0.0334 [get_ports {ss6[1]}]
set_load -pin_load 0.0334 [get_ports {ss6[0]}]
set_load -pin_load 0.0334 [get_ports {ss7[7]}]
set_load -pin_load 0.0334 [get_ports {ss7[6]}]
set_load -pin_load 0.0334 [get_ports {ss7[5]}]
set_load -pin_load 0.0334 [get_ports {ss7[4]}]
set_load -pin_load 0.0334 [get_ports {ss7[3]}]
set_load -pin_load 0.0334 [get_ports {ss7[2]}]
set_load -pin_load 0.0334 [get_ports {ss7[1]}]
set_load -pin_load 0.0334 [get_ports {ss7[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {interrupt_gpio_in}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {nrst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {keypad_input[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {memory_data_in[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {programmable_gpio_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
